name: epraga
description: E-praga sistema de controle de pragas - 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: any # Para animações
  font_awesome_flutter: ^8.8.1 # Para icones padrões
  http: ^0.12.1 # Comunicação REST e SOAP
  map_launcher: ^0.12.0 # Para abertura de dados do mapa
  mask_text_input_formatter: ^1.0.6 # Para mascaras de formulários
  provider: ^4.1.3 # Gerenciamento de dados
  shared_preferences: ^0.5.7+3 # Para shared preferences
  sqflite: ^1.3.1 # Para banco de dados
  toast: ^0.1.5 # Toas com mensagens

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/logo/
   - assets/flare/
  fonts:
    - family: SystemAnalysis
      fonts:
        - asset: fonts/SystemAnalysis/SystemAnalysis.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf