name: epraga
description: Aplicativo para controle de pragas - EPraga
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^1.1.2 # Para efeitos visuais
  camera: ^0.5.8+5 # Para dados da câmera
  compressimage: ^0.1.1 # Para tratamento de imagens
  device_info: ^0.4.2+8 # Para coleta de informações do dispositivo
  flare_flutter: any # Para animações
  font_awesome_flutter: ^8.8.1 # Para icones padrões
  geolocator: ^6.0.0+4 # Coleta de localização
  http: ^0.12.1 # Comunicação REST e SOAP
  imei_plugin: ^1.2.0 # Request IMEI'S
  image_crop: ^0.3.2 # cortar imagens
  map_launcher: ^0.12.0 # Para abertura de dados do mapa
  mask_text_input_formatter: ^1.0.6 # Para mascaras de formulários
  path_provider: ^1.6.18 # Para coleta dos dados - Cria o provider
  permission_handler: ^3.0.0 # Solicitar permissões de acesso
  photo_view: ^0.10.1 # Visualização de imagens
  provider: ^4.1.3 # Gerenciamento de dados
  sqflite: ^1.3.1+1 # Para banco de dados - Coleta offline
  toast: ^0.1.5 # Toas com mensagens

  
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/animation/
   - assets/images/
  fonts:
    - family: SystemAnalysis
      fonts:
        - asset: fonts/SystemAnalysis/SystemAnalysis.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf